### ISSUE TITLE
Remove deals graph

### ISSUE THREAD

**Issue by rimenes** [lucianot/dealbook#16]
Should we remove the Deals graph? To me it seems to be a half baked feature without any real use case.

![Deal graph]
(https://www.evernote.com/shard/s31/sh/39b29c8e-0979-4666-ae3b-c72e0fd13ae8/70214b229e14487248a02b4a44e3fd0b/res/b4cc856d-c0ea-4f5f-a436-e2415315d2dd/skitch.png)

/cc @lucianot

**Comment by lucianot** [comment]
@rimenes 
This was a "feature" submitted by a user, mostly for experimentation. Normally I would agree to remove it, but we also want to stimulate user collaboration. I guess we can leave it for now, it seems pretty isolated and harmless.
